name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: pnpm setup
        uses: pnpm/action-setup@v6

      - name: node setup
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: install
        run: pnpm i --frozen-lockfile

      - name: audit
        run: pnpm audit --audit-level low

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test

      - name: release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
